import Header from '@/pages/Header'
import './globals.css'
import { Inter } from 'next/font/google'
import Bar from '@/pages/Bar-1'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Zona Sana App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}
      </body>

    </html>
  )
}
